pygments: true
paginate: 5
comments: true
# "none" actually means /:categories/:title.html
permalink: none
title: "Sarah Wiger - Graphic Designer"
author: Sarah Wiger
description: "Graphic designer experienced in creating inspired print and web solutions for boutique brands in the fashion industry.  Affordable rates and quick turnaround."
tagline: cute shit here 

